apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-redshift-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-redshift
  template:
    metadata:
      labels:
        app: mcp-redshift
    spec:
      containers:
      - name: mcp-redshift-server
        image: <your-ecr-repo>/mcp-redshift-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: REDSHIFT_CLUSTER_ID
          value: "<your-redshift-cluster-id>"
        - name: REDSHIFT_DATABASE
          value: "<your-database-name>"
        - name: REDSHIFT_DB_USER
          value: "<your-db-user>"
        - name: MCP_API_KEY
          value: "your-secure-api-key-here"
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-redshift-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: mcp-redshift
